config/routes.rb
EZBORROW_URL = (ENV['EZBORROW_URL'] || "https://library.nyu.edu/services/borrowing/from-non-nyu-libraries/e-zborrow/")

Rails.application.routes.draw do
  providers = Regexp.union(Devise.omniauth_providers.map(&:to_s))
  use_doorkeeper do
    controllers :authorizations => 'doorkeeper/custom_authorizations'
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions' }
  devise_scope :user do
    root to: 'wayf#index', as: 'root'
    get 'users/:provider/:id(/:institution)', to: 'users#show', as: 'user',
      constraints: { provider: providers, id: /[^\/]+/ }
    get 'logout(/:institution)', to: 'users/sessions#destroy', as: :logout
    get 'auth/:auth_type(/:institution)', to: 'users/sessions#new', as: :auth
    get 'login/passive', to: 'users/client_passive_login#client_passive_login'
    get 'login/passive_shibboleth', to: 'users/client_passive_login#shibboleth_passive_login', as: :passive_shibboleth
    get 'users/show', to: 'users#show'
    match 'passthru', to: 'users/passthru#passthru', via: [:post, :get], as: :passthru
  end
  get 'login(/:institution)', to: 'wayf#index', as: :login
  get 'logged_out(/:institution)', to: 'wayf#logged_out', as: :logged_out
  namespace :api do
    namespace :v1 do
      get '/user' => "users#show", defaults: { format: :json }
    end
  end
  get 'pds' => redirect { |params, request| "#{ENV['PDS_URL']}/pds?#{request.query_string}" }
  get '/ezborrow(/:institution)' => redirect { EZBORROW_URL }
  get 'ezproxy' => redirect { |params, request| "#{ENV['EZPROXY_URL']}/login?#{request.query_string}" }
  get 'healthcheck' => 'root#healthcheck'
end

app/controllers/wayf_controller.rb
class WayfController < ApplicationController
  respond_to :html
  # Don't allow users to visit the logged_out page with GET, force a logout if that happens
  before_action :redirect_to_logout, only: [:logged_out], if: -> { user_signed_in? }

  def index
    if cookies[:institution_from_url].present?
      institution = cookies.delete(:institution_from_url).downcase
      redirect_to login_path(institution: institution)
    end
  end

  private

  def redirect_to_logout
    redirect_to logout_path
  end

end

app/views/wayf/_cu.html.erb
<div class="row">
  <h1 class="heading"><%= t('application.header_html') %></h1>
</div>
<div class="row">
  <!-- Link to CU auth -->
  <div id="cu-login" class="col-sm-12 primary-login">
    <h2><%= link_to t('application.cu.link_text'), auth_path(:cu, current_institution.code.downcase, redirect_uri: @redirect_uri) %></h2>
  </div>
</div>
<!-- Link to the rest of the secondary logins -->
<div class="row">
  <% institution.views["login"]["secondary"].each do |option| %>
    <%= render "wayf/auth_squares/#{option}" %>
  <% end %>
  <!-- Link to visitor square -->
  <%= render "wayf/auth_squares/visitor" %>
</div>

app/views/wayf/_hsl.html.erb
<div class="row">
  <h1 class="heading"><%= t('application.header_html') %></h1>
</div>
<div class="row">
  <!-- Link to NYU Shibboleth auth -->
  <div id="nyu_shibboleth-login" class="col-sm-9 primary-login">
    <h2><%= link_to t('application.nyu.link_text'), user_nyu_shibboleth_omniauth_authorize_path(institution: current_institution.code, auth_type: :nyu, redirect_uri: @redirect_uri) %></h2>
  </div>
  <!-- Link to the first secondary login auth in the list -->
  <%- option = institution.views["login"]["secondary"].first -%>
  <%= render "wayf/auth_squares/secondary_square", option: option %>
</div>

app/views/wayf/_ns.html.erb
<div class="row">
  <h1 class="heading"><%= t('application.header_html') %></h1>
</div>
<div class="row">
  <!-- Link to New School auth -->
  <div id="ns-login" class="col-sm-12 primary-login">
    <h2><%= link_to t('application.ns.link_text'), auth_path(:ns, current_institution.code.downcase, redirect_uri: @redirect_uri) %></h2>
  </div>
</div>
<!-- Link to the rest of the secondary logins -->
<div class="row">
  <% institution.views["login"]["secondary"].each do |option| %>
    <%= render "wayf/auth_squares/#{option}" %>
  <% end %>
  <!-- Link to visitor square -->
  <%= render "wayf/auth_squares/visitor" %>
</div>

app/views/wayf/_nysid.html.erb
<div class="row">
  <h1 class="heading"><%= t('application.header_html') %></h1>
</div>
<div class="row">
  <!-- Link to NYSID auth -->
  <div id="nysid-login" class="col-sm-12 primary-login">
    <h2><%= link_to t('application.nysid.link_text'), auth_path(:nysid, current_institution.code.downcase, redirect_uri: @redirect_uri) %></h2>
  </div>
</div>
<!-- Link to the rest of the secondary logins -->
<div class="row">
  <% institution.views["login"]["secondary"].each do |option| %>
    <%= render "wayf/auth_squares/#{option}" %>
  <% end %>
  <!-- Link to visitor square -->
  <%= render "wayf/auth_squares/visitor" %>
</div>

app/views/wayf/_nyu.html.erb
<!-- Link to NYU Shibboleth and the first secondary login -->
<div class="row">
  <h1 class="heading"><%= t('application.header_html') %></h1>
</div>
<div class="row">
  <!-- Link to NYU Shibboleth auth -->
  <div id="nyu_shibboleth-login" class="col-sm-9 primary-login">
    <h2><%= link_to t('application.nyu.link_text'), user_nyu_shibboleth_omniauth_authorize_path(institution: current_institution.code, auth_type: :nyu, redirect_uri: @redirect_uri) %></h2>
  </div>
  <!-- Link to the first secondary login auth in the list -->
  <%- option = institution.views["login"]["secondary"].first -%>
  <%= render "wayf/auth_squares/#{option}" %>
</div>
<!-- Link to the rest of the secondary logins -->

<div class="row">
  <% institution.views["login"]["secondary"][1..-1].each do |option| %>
    <%= render "wayf/auth_squares/#{option}" %>
  <% end %>
  <!-- Link to visitor square -->
  <%= render "wayf/auth_squares/visitor" %>
</div>

app/views/wayf/_nyuad.html.erb
<div class="row">
  <h1 class="heading"><%= t('application.header_html') %></h1>
</div>
<div class="row">
  <!-- Link to NYU Shibboleth auth -->
  <div id="nyu_shibboleth-login" class="col-sm-9 primary-login">
    <h2><%= link_to t('application.nyu.link_text'), user_nyu_shibboleth_omniauth_authorize_path(institution: current_institution.code, auth_type: :nyu, redirect_uri: @redirect_uri) %></h2>
  </div>
  <!-- Link to the first secondary login auth in the list -->
  <%- option = institution.views["login"]["secondary"].first -%>
  <%= render "wayf/auth_squares/secondary_square", option: option %>
</div>

app/views/wayf/_nyush.html.erb
<div class="row">
  <h1 class="heading"><%= t('application.header_html') %></h1>
</div>
<div class="row">
  <!-- Link to NYU Shibboleth auth -->
  <div id="nyu_shibboleth-login" class="col-sm-9 primary-login">
    <h2><%= link_to t('application.nyu.link_text'), user_nyu_shibboleth_omniauth_authorize_path(institution: current_institution.code, auth_type: :nyu, redirect_uri: @redirect_uri) %></h2>
  </div>
  <!-- Link to the first secondary login auth in the list -->
  <%- option = institution.views["login"]["secondary"].first -%>
  <%= render "wayf/auth_squares/secondary_square", option: option %>
</div>

app/views/wayf/index.html.erb
<div id="logins" class="container options-container<%= " #{institution.code.to_s.downcase}-container" %>">
  <div class="inner-container">
    <% if request.path.include? "visitor" %>
      <%= render "visitor" %>
    <% else %>
      <%= render "wayf/#{institution.code.to_s.downcase}" %>
    <% end %>
    <%= render "wayf/help/#{institution.code.to_s.downcase}_help" rescue render "wayf/help/help" %>
  </div>
</div>

app/views/wayf/logged_out.html.erb
<div id="logins" class="container options-container">
  <div class="inner-container">
    <div class="row">
      <h1 class="heading"><%= t('application.logged_out') %></h1>
    </div>
    <div class="row logged_out_text">
      <p>Exit your browser to log out everywhere - keep other people from logging into your account</p>
    </div>
    <div class="row">
      <h2 class="help">
        <%= fa_icon "question-circle 2x", class: "circle", 'aria-hidden' => 'true' %>
        <span class="help_text">
          <%= link_to t('application.logged_out_footer_html'), 'https://library.nyu.edu/ask', target: :_blank %>
        </span>
      </h2>
    </div>
  </div>
</div>